# In robot_bringup/config/local_planner.yaml

local_planner: # 节点名，与启动文件中的 name='...' 对应
  ros__parameters:
    # --- 文件与机器人尺寸 ---
    pathFolder: "" # 这个值需要在启动文件中动态设置
    vehicleLength: 0.6
    vehicleWidth: 0.6
    
    # --- 传感器与坐标系 ---
    sensorOffsetX: 0.0 # 可以通过启动参数覆盖
    sensorOffsetY: 0.0 # 可以通过启动参数覆盖
    
    # --- 核心规划算法参数 ---
    twoWayDrive: false # 可以通过启动参数覆盖
    laserVoxelSize: 0.05
    terrainVoxelSize: 0.2
    useTerrainAnalysis: true
    checkObstacle: true
    checkRotObstacle: false
    adjacentRange: 3.5
    pointPerPathThre: 2

    # --- 地形与成本参数 ---
    obstacleHeightThre: 0.15
    groundHeightThre: 0.05
    costHeightThre1: 0.1
    costHeightThre2: 0.05
    useCost: false
    
    # --- 路径评估与选择 ---
    minRelZ: -0.4
    maxRelZ: 0.3
    dirWeight: 0.02
    dirThre: 90.0
    dirToVehicle: false

    # --- 路径动态缩放 ---
    pathScale: 1.0
    minPathScale: 0.75
    pathScaleStep: 0.25
    pathScaleBySpeed: true
    minPathRange: 1.0
    pathRangeStep: 0.5
    pathRangeBySpeed: true

    # --- 目标处理与自主模式 ---
    pathCropByGoal: true
    maxSpeed: 1.0 # 可以通过启动参数覆盖
    autonomyMode: true # 可以通过启动参数覆盖
    autonomySpeed: 0.5 # 可以通过启动参数覆盖
    joyToSpeedDelay: 2.0 # 可以通过启动参数覆盖
    joyToCheckObstacleDelay: 5.0
    goalClearRange: 0.4
    goalBehindRange: 0.8
    freezeAng: 90.0
    freezeTime: 2.0
    goalX: 0.0 # 可以通过启动参数覆盖
    goalY: 0.0 # 可以通过启动参数覆盖