# In robot_bringup/config/terrain_analysis.yaml

terrainAnalysis: # 节点名，与XML中的 name='...' 对应
  ros__parameters:
    scanVoxelSize: 0.05
    decayTime: 1.0
    noDecayDis: 1.75
    clearingDis: 8.0
    useSorting: true
    quantileZ: 0.25
    considerDrop: false
    limitGroundLift: false
    maxGroundLift: 0.15
    clearDyObs: true
    minDyObsDis: 0.3
    minDyObsAngle: 0.0
    minDyObsRelZ: -0.3
    absDyObsRelZThre: 0.2
    minDyObsVFOV: -28.0
    maxDyObsVFOV: 33.0
    minDyObsPointNum: 1
    noDataObstacle: false
    noDataBlockSkipNum: 0
    minBlockPointNum: 10
    vehicleHeight: 0.63
    voxelPointUpdateThre: 100
    voxelTimeUpdateThre: 2.0
    minRelZ: -0.10
    maxRelZ: 0.15
    disRatioZ: 0.0