# In robot_bringup/config/terrain_analysis_ext.yaml

terrainAnalysisExt: # 节点名，与旧launch文件中的 name='...' 对应
  ros__parameters:
    scanVoxelSize: 0.1
    decayTime: 4.0
    noDecayDis: 0.0
    clearingDis: 30.0
    useSorting: true
    quantileZ: 0.1
    vehicleHeight: 1.5
    voxelPointUpdateThre: 100
    voxelTimeUpdateThre: 2.0
    lowerBoundZ: -2.5
    upperBoundZ: 1.0
    disRatioZ: 0.1
    checkTerrainConn: false # 可以通过启动参数覆盖
    terrainConnThre: 0.5
    terrainUnderVehicle: -0.75
    ceilingFilteringThre: 2.0
    localTerrainMapRadius: 4.0